### ISSUE TITLE
One stream just can read one time default

### ISSUE THREAD

**Issue by shps951023** [shps951023/MiniExcel#103]

**Comment by shps951023** [comment]
```
System.ArgumentException
  HResult=0x80070057
  Message=Cannot use read mode on a non-readable stream.
  Source=System.IO.Compression
  StackTrace:
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at MiniExcelLibs.OpenXml.ExcelOpenXmlSheetReader.<QueryImpl>d__8.MoveNext() in D:\git\MiniExcel\src\MiniExcel\OpenXml\ExcelOpenXmlSheetReader.cs:line 183
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MiniExcelLibs.Tests.MiniExcelHelperTests.FixDimensionJustOneColumnParsingError_Test() in D:\git\MiniExcel\tests\MiniExcelTests\MiniExcelHelperTests.cs:line 268

  This exception was originally thrown at this call stack:
    [External Code]
    MiniExcelLibs.OpenXml.ExcelOpenXmlSheetReader.QueryImpl(System.IO.Stream, bool) in ExcelOpenXmlSheetReader.cs
    [External Code]
    MiniExcelLibs.Tests.MiniExcelHelperTests.FixDimensionJustOneColumnParsingError_Test() in MiniExcelHelperTests.cs
```
![image](https://user-images.githubusercontent.com/12729184/111500250-be1af980-877e-11eb-8b0c-d9df0911e01e.png)
