### ISSUE TITLE
Query Support Sheet Xml c without r

### ISSUE THREAD

**Issue by shps951023** [shps951023/MiniExcel#2]
Normal data like :  
```xml
<?xml version="1.0" encoding="utf-8"?>
<worksheet xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <dimension ref="A1:B2" />
    <sheetViews>
        <sheetView workbookViewId="0" />
    </sheetViews>
    <sheetFormatPr defaultRowHeight="15" />
    <sheetData>
        <row r="1">
            <c r="A1" s="0" t="s">
                <v>0</v>
            </c>
            <c r="B1" s="0">
                <v>44257.384891898146</v>
            </c>
        </row>
        <row r="2">
            <c r="A2" s="0">
                <f>=MID(A1, 7, 5)</f>
            </c>
            <c r="B2" s="0">
                <v>123</v>
            </c>
        </row>
    </sheetData>
    <headerFooter />
</worksheet>
```

But simple data will like :  
```xml
<?xml version="1.0" encoding="utf-8"?>
<x:worksheet xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <x:sheetData>
        <x:row>
            <x:c t="n">
                <x:v>1</x:v>
            </x:c>
            <x:c t="str">
                <x:v>"&lt;&gt;+}{\nHello World</x:v>
            </x:c>
            <x:c t="b">
                <x:v>1</x:v>
            </x:c>
            <x:c t="d">
                <x:v>2021-03-02T08:47:12</x:v>
            </x:c>
        </x:row>
        <x:row>
            <x:c t="n">
                <x:v>1</x:v>
            </x:c>
            <x:c t="str">
                <x:v>"&lt;&gt;+}{\nHello World</x:v>
            </x:c>
            <x:c t="b">
                <x:v>1</x:v>
            </x:c>
            <x:c t="d">
                <x:v>2021-03-02T08:47:12</x:v>
            </x:c>
        </x:row>
    </x:sheetData>
</x:worksheet>
```

![image](https://user-images.githubusercontent.com/12729184/109593834-ab80ad80-7b4c-11eb-931d-7be7bf8ae886.png)

**Comment by shps951023** [comment]
CloseXML not support c without r, it'll show `Input string was not in a correct format.`

![image](https://user-images.githubusercontent.com/12729184/109594570-fea73000-7b4d-11eb-9625-9ee3716b75b1.png)

```C#
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at ClosedXML.Excel.XLWorkbook.LoadCells(SharedStringItem[] sharedStrings, Stylesheet s, NumberingFormats numberingFormats, Fills fills, Borders borders, Fonts fonts, Dictionary`2 sharedFormulasR1C1, XLWorksheet ws, Dictionary`2 styleList, Cell cell, Int32 rowIndex) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 1664
   at ClosedXML.Excel.XLWorkbook.LoadRows(Stylesheet s, NumberingFormats numberingFormats, Fills fills, Borders borders, Fonts fonts, XLWorksheet ws, SharedStringItem[] sharedStrings, Dictionary`2 sharedFormulasR1C1, Dictionary`2 styleList, Row row) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 2121
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 266
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 43
   at ClosedXML.Excel.XLWorkbook.Load(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 33
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 718
   at ClosedXML.Excel.XLWorkbook..ctor(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 709
   at UserQuery.Main() in C:\Users\Wei\AppData\Local\Temp\LINQPad6\_zeygkceo\tqolpc\LINQPadQuery:line 5
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
```

**Comment by shps951023** [comment]
Try EPPLUS also not support c without r, it'll show Input string was not in a correct format.
![image](https://user-images.githubusercontent.com/12729184/109594815-62c9f400-7b4e-11eb-8f49-82ea21b15926.png)

It looks like can not support it. because it need more check logic costing.

**Comment by shps951023** [comment]
Try NPOI also not support c without r
![image](https://user-images.githubusercontent.com/12729184/109613533-40df6a00-7b6c-11eb-9ba6-64b53945fb96.png)

**Comment by shps951023** [comment]
ExcelDataReader can read  
![image](https://user-images.githubusercontent.com/12729184/111252780-de4a9b80-864c-11eb-83c4-ecddea93284f.png)

**Comment by shps951023** [comment]
![Uploading image.png…]()

**Comment by shps951023** [comment]
It can read first row to know maxColumnIndex
![image](https://user-images.githubusercontent.com/12729184/111282615-28497680-8679-11eb-95b6-a60bb69c199f.png)

```xml
<?xml version="1.0" encoding="utf-8"?>
<x:worksheet xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <x:sheetData>
        <x:row>
            <x:c t="n">
                <x:v>1</x:v>
            </x:c>
            <x:c t="str">
                <x:v>"&lt;&gt;+}{\nHello World</x:v>
            </x:c>
            <x:c t="b">
                <x:v>1</x:v>
            </x:c>
            <x:c t="d">
                <x:v>2021-03-16T16:59:12</x:v>
            </x:c>
            <x:c s="1">
                <x:v>44271.70778590278</x:v>
            </x:c>
        </x:row>
        <x:row>
            <x:c t="n">
                <x:v>1</x:v>
            </x:c>
            <x:c t="str">
                <x:v>"&lt;&gt;+}{\nHello World</x:v>
            </x:c>
            <x:c t="d">
                <x:v>2021-03-16T16:59:12</x:v>
            </x:c>
            <x:c s="1">
                <x:v>44271.70778590278</x:v>
            </x:c>
        </x:row>
    </x:sheetData>
</x:worksheet>
```

**Comment by shps951023** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<x:worksheet xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <x:sheetData>
        <x:row>
            <x:c t="n">
                <x:v>1</x:v>
            </x:c>
            <x:c s="1">
                <x:v>44271.798862407406</x:v>
            </x:c>
        </x:row>
        <x:row>
            <x:c t="n">
                <x:v>1</x:v>
            </x:c>
            <x:c t="str">
                <x:v>"&lt;&gt;+}{\nHello World</x:v>
            </x:c>
            <x:c t="b">
                <x:v>1</x:v>
            </x:c>
            <x:c t="d">
                <x:v>2021-03-16T19:10:21</x:v>
            </x:c>
            <x:c s="1">
                <x:v>44271.79886243056</x:v>
            </x:c>
        </x:row>
    </x:sheetData>
</x:worksheet>
```
