### ISSUE TITLE
MiniExcelIssueTests.Issue255 Non-static method requires a target.

### ISSUE THREAD

**Issue by shps951023** [shps951023/MiniExcel#260]
```
[xUnit.net 00:00:08.12]     MiniExcelLibs.Tests.MiniExcelIssueTests.Issue255 [FAIL]
[xUnit.net 00:00:08.12]       System.Reflection.TargetException : Non-static method requires a target.
[xUnit.net 00:00:08.12]       Stack Trace:
[xUnit.net 00:00:08.12]            at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
[xUnit.net 00:00:08.12]            at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[xUnit.net 00:00:08.12]            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[xUnit.net 00:00:08.12]         /home/runner/work/MiniExcel/MiniExcel/src/MiniExcel/OpenXml/ExcelOpenXmlSheetWriter.cs(284,0): at MiniExcelLibs.OpenXml.ExcelOpenXmlSheetWriter.GenerateSheetByProperties(StreamWriter writer, MiniExcelZipArchive archive, IEnumerable value, List`1 props, Int32 rowCount, Int32 xIndex, Int32 yIndex)
[xUnit.net 00:00:08.13]         /home/runner/work/MiniExcel/MiniExcel/src/MiniExcel/OpenXml/ExcelOpenXmlSheetWriter.cs(214,0): at MiniExcelLibs.OpenXml.ExcelOpenXmlSheetWriter.CreateSheetXml(Object value, Boolean printHeader, MiniExcelZipArchive archive, Dictionary`2 packages, String sheetPath)
[xUnit.net 00:00:08.13]         /home/runner/work/MiniExcel/MiniExcel/src/MiniExcel/OpenXml/ExcelOpenXmlSheetWriter.cs(70,0): at MiniExcelLibs.OpenXml.ExcelOpenXmlSheetWriter.SaveAs(Object value, String sheetName, Boolean printHeader, IConfiguration configuration)
[xUnit.net 00:00:08.13]         /home/runner/work/MiniExcel/MiniExcel/src/MiniExcel/MiniExcel.cs(28,0): at MiniExcelLibs.MiniExcel.SaveAs(Stream stream, Object value, Boolean printHeader, String sheetName, ExcelType excelType, IConfiguration configuration)
[xUnit.net 00:00:08.13]         /home/runner/work/MiniExcel/MiniExcel/src/MiniExcel/MiniExcel.cs(19,0): at MiniExcelLibs.MiniExcel.SaveAs(String path, Object value, Boolean printHeader, String sheetName, ExcelType excelType, IConfiguration configuration)
[xUnit.net 00:00:08.13]         /home/runner/work/MiniExcel/MiniExcel/tests/MiniExcelTests/MiniExcelIssueTests.cs(58,0): at MiniExcelLibs.Tests.MiniExcelIssueTests.Issue255()
```

**Comment by shps951023** [comment]
![image](https://user-images.githubusercontent.com/12729184/122647648-d4f33280-d157-11eb-9c1b-002833d94bf1.png)

**Comment by shps951023** [comment]
![image](https://user-images.githubusercontent.com/12729184/122651106-3f609e80-d169-11eb-9c57-b267e5b81110.png)
![image](https://user-images.githubusercontent.com/12729184/122651117-4b4c6080-d169-11eb-9a51-a9ec647a35c3.png)
