### ISSUE TITLE
MiniExcelHelper.Create compatible problem

### ISSUE THREAD

**Issue by shps951023** [shps951023/MiniExcel#5]
ClosedXML can't read
![image](https://user-images.githubusercontent.com/12729184/109614533-ba2b8c80-7b6d-11eb-95c0-b22bc985ed39.png)

```xml

The specified package is invalid. The main part is missing.
--

   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(String path, Boolean readWriteMode)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 42
   at ClosedXML.Excel.XLWorkbook.Load(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 33
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 718
   at ClosedXML.Excel.XLWorkbook..ctor(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 709
   at UserQuery.Main() in C:\Users\Wei\AppData\Local\Temp\LINQPad6\_zeygkceo\esvuvz\LINQPadQuery:line 5
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
--



```

**Comment by shps951023** [comment]
office 2007 to 365 can read
![image](https://user-images.githubusercontent.com/12729184/109614813-12fb2500-7b6e-11eb-922c-5b9dc81eab8d.png)
