### ISSUE TITLE
Sheet First Row Head same key

### ISSUE THREAD

**Issue by shps951023** [shps951023/MiniExcel#70]
![image](https://user-images.githubusercontent.com/12729184/110878141-9a3a5c80-8315-11eb-89ab-5ee6ee07d7ec.png)
![image](https://user-images.githubusercontent.com/12729184/110878160-a58d8800-8315-11eb-87f5-7977c9edcb45.png)

**Comment by shps951023** [comment]
Chose between get last one or first one

**Comment by shps951023** [comment]
![image](https://user-images.githubusercontent.com/12729184/111097610-d3283a80-857c-11eb-9513-8358d512d1bc.png)
```
System.ArgumentException
  HResult=0x80070057
  Message=An element with the same key 'HelloWorld' already exists in the ExpandoObject. (Parameter 'key')
  Source=System.Linq.Expressions
  StackTrace:
   at System.Dynamic.ExpandoObject.TrySetValue(Object indexClass, Int32 index, Object value, String name, Boolean ignoreCase, Boolean add)
   at System.Dynamic.ExpandoObject.TryAddMember(String key, Object value)
   at System.Dynamic.ExpandoObject.System.Collections.Generic.IDictionary<System.String,System.Object>.Add(String key, Object value)
   at MiniExcelLibs.Utils.Helpers.GetEmptyExpandoObject(Dictionary`2 hearrows) in D:\git\MiniExcel\src\MiniExcel\Utils\Helpers.cs:line 56
   at MiniExcelLibs.OpenXml.ExcelOpenXmlSheetReader.<QueryImpl>d__8.MoveNext() in D:\git\MiniExcel\src\MiniExcel\OpenXml\ExcelOpenXmlSheetReader.cs:line 267
   at MiniExcelLibs.MiniExcel.<Query>d__4`1.MoveNext() in D:\git\MiniExcel\src\MiniExcel\MiniExcel.cs:line 179
   at System.Linq.Enumerable.EnumerablePartition`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MiniExcelLibs.Tests.MiniExcelHelperTests.LargeFileQueryStrongTypeMapping_Test() in D:\git\MiniExcel\tests\MiniExcelTests\MiniExcelHelperTests.cs:line 154
```

**Comment by shps951023** [comment]
Now same column name cells, right cell will replace left cell

**Comment by shps951023** [comment]
Like Dapper same column name use left one 

![image](https://user-images.githubusercontent.com/12729184/111106285-c5c87b80-858f-11eb-8785-e4a7ad7775fa.png)

![image](https://user-images.githubusercontent.com/12729184/111106322-dc6ed280-858f-11eb-8d62-3d1276a975ec.png)

**Comment by shps951023** [comment]
Now Same column name use last right one
